### ISSUE TITLE
Module 4: Shiny plot not appearing

### ISSUE THREAD

**Issue by emmabonham** [Watts-College/cpp-526-spr-2023#10]
I am running my code and it just returns <shiny.render.function> and I can't see what my plot looks like. Even when I run the examples it does this. Am I forgetting something or is this a technical issue? Thank you!
![image](https://user-images.githubusercontent.com/122310998/216725631-9de2184a-4c37-49dd-b8f8-8dd0937b877a.png)

**Comment by drcarlson-asu** [comment]
Hi emmieleen,
Take a look here on ideas on how you can troubleshoot this: https://shiny.rstudio.com/tutorial/written-tutorial/lesson4/

**Comment by emmabonham** [comment]
I think I got it, thank you!
