### ISSUE TITLE
Lab 5 Part II

### ISSUE THREAD

**Issue by kybrwallace** [Watts-College/cpp-526-spr-2023#14]
Hi,

I'm really struggling with creating the table for question 2 of part II. For some reason my numbers are off. I suspect it's because my n number is incorrect and I can't figure out how to fix it. This is what I have so far:

```{r}

dat %>% 
  group_by(age, hour12) %>% 
  summarize(n = n()) %>%  
  group_by(age) %>%         
  mutate(n.age = sum(n)) %>%
  mutate(n.hour = sum(hour12 == "7 AM")) %>% 
  mutate(p = round(n / n.age, 2)) %>%
  filter(hour12 == "7 AM")

```

![output](https://user-images.githubusercontent.com/121522107/217968557-00fe385a-883d-481b-8623-b54f72ec2ca8.PNG)

**Comment by emmabonham** [comment]
I am also getting these numbers, but I checked it with the line...
sum((dat$hour12 == '7 AM' & dat$age == 'Age 18-25'), na.rm = T)
and it is coming out with the same numbers, so I think n is correct.

I am guessing the data has been updated since, but not the template with the hint.

**Comment by kybrwallace** [comment]
I hope that's the case. I've been looking at this for awhile and keep getting the same numbers. 😵

**Comment by tdeconcini** [comment]
Hi I noticed the same thing!

**Comment by tdeconcini** [comment]
I'm also really struggling with the columns, can anyone help me with some hints here? I've tried a bunch of different things and none of them have worked: 
dat %>% 
  group_by(age, hour12) %>% 
  summarize(n = n()) %>%    # Partial solution
  group_by(age) %>%           # Requires two new variables in 'mutate()'
  mutate(n.age = sum(n),
         n.hour = (hour12),
         p = round(n / n.age, 2)) %>%
        #  p.age = round(n/n.age, 2)) %>%
         #p.hour = ) %>% # Lastly, requires function 'filter()
  filter(hour12 == "7 AM")

**Comment by terasum** [comment]
I have the same question, and I'm curious about your data like `n.age` doesn't equal to instruction's initial value,does this matter?

the initial values:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/20042193/218378760-bec5ce71-ad14-4408-b18e-799fd6673329.png">

and my output:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/20042193/218378777-e165a174-9477-42c7-b7f1-b78874510ecd.png">
