### ISSUE TITLE
Lab 5 Part 3 Question 4

### ISSUE THREAD

**Issue by kybrwallace** [Watts-College/cpp-526-spr-2023#15]
I am absolutely driving the struggle bus when it comes to this lab. I'm almost finished, but I'm stuck on Part 3 Question 4. I cannot wrap my brain around how to calculate a proportion for harmful accidents. 
![im-not-having-a-good-time-im-not-having-fun](https://user-images.githubusercontent.com/121522107/218274871-645a8b5f-8b62-4209-bae6-cc37b908749b.gif)

This is the code I used for question 3, which I assume would be similar for Q4? I tried doing  summarize(total = mean(Totalinjuries + Totalfatalities) / n) but that just returns an error message. 

dat %>%
  group_by(hour) %>%
  summarize(total = mean(Totalinjuries + Totalfatalities)) %>%
  plot(type = "b",
       bty = "n",
       pch = 19,
       cex = 2,
       xlab = "Hour of the Day",
       ylab = "Proportion of Accidents Resulting in Harm",
       main = "Proportion of Accidents that Result in Injuries or Fatalities")

**Comment by tdeconcini** [comment]
Try mutating! and take a look at the code in Part 1. #6, that really helped me!

**Comment by terasum** [comment]
@tdeconcini Thank you for inspiring me!
