### ISSUE TITLE
Lab 6 Step 3

### ISSUE THREAD

**Issue by haileyjudd** [Watts-College/cpp-526-spr-2023#17]
Okay, I feel like I'm going in circles on this question (maybe it's just a fried brain type of week). I've got my code to create the table and it creates the correct output. Except I can't seem to keep the group_by in the final output. I'm getting multiple lines of code for each year, but each line of data is all the same. I've tried rearranging the code and adding another group_by, but am missing something. 

````{r}

dat3 %>% 
  group_by(yearID, teamID) %>%
  mutate(team.budget = sum(salary.adj) ) %>% 
  mutate(cost.per.win = (team.budget / W) / 100000) %>% 
  summarize(n=n(),
            team.budget,
            cost.per.win) 
  
 
````

![image](https://user-images.githubusercontent.com/123833216/219827062-dd0edbba-8380-41da-aedd-97c28bcb1eca.png)

**Comment by emmabonham** [comment]
I am struggling with this issue as well but for the first step. Not sure what I am doing wrong.

**Comment by emmabonham** [comment]
Maybe we can discuss how we did the first step- You were able to get it to work and I wasn't, so that might reveal what the issue is and why it isn't grouping correctly.

**Comment by haileyjudd** [comment]
In the first step, I was able to get the table using:

```{r}

Salaries %>% 
    group_by(yearID, teamID) %>% 
    summarize(n=n(),
              team.budget = sum(salary.adj))

```

This kept the table grouped with one year per each team.

**Comment by emmabonham** [comment]
Okay, looks like I made mine more complicated than it needed to be haha. This is what I did. I'm looking for the difference in our codes that makes it not group properly.

Salaries %>%
  select(teamID, yearID, salary.adj) %>% 
  group_by(teamID) %>% 
  mutate(n = n()) %>% 
  mutate(team.bud = sum(salary.adj)) %>% 
  summarize(teamID, yearID, n, team.bud)

**Comment by emmabonham** [comment]
Weird. It looks like the order of "group_by" inputs affects it, which I didn't even consider, but also when I use "mutate" instead of putting the functions in "summarize" it doesn't like that either.

**Comment by haileyjudd** [comment]
Yes, I've been trying to play around with the order of each function, using mutate vs summarize, and I either run into errors or the table just not grouping.

**Comment by emmabonham** [comment]
I ended up calculating team.bud and cost.p.win and making them their own columns prior to using the pipe operator and then putting yearID, teamID, and both of those new columns into group_by. Then just summarizing with n. It's working now but I feel like there's probably a better way to do that haha.

**Comment by emmabonham** [comment]
Actually now the team.bud isn't looking right, so I'm not sure. -- I changed it to use the team.bud the same way as step one but then did the new column with cost.p.win. I am not sure why the cost.p.win messes up the grouping.

**Comment by kybrwallace** [comment]
So this is what I did for step 1. Then for step 2 I did a left join. For step 3 I did a mutate() with to calculate a cost per win under my team_sals object. Is this how you set yours up?

total_sals <- Salaries %>% 
  group_by(teamID, yearID) %>% 
  summarize(players = n(),
    total_cost = sum(salary.adj, na.rm = TRUE))

**Comment by emmieleen** [comment]
For 1 I ended up just using summarize instead of mutate and fixing the order of my "group_by". For 2 I used merge. For 3 I did it the same as 1 but I just made a new column in the data set for the cost.p.win data. But I think what you did should work too! Are you still having issues?

**Comment by emmabonham** [comment]
I ended up doing something else, but I think it's working now. But that sounds like it's working too!

**Comment by emmabonham** [comment]
Sorry for all of my comments. I realized the "fix" I used made my numbers wrong. I am getting the right numbers now but I am still struggling with this grouping issue and I can't figure out why.
