### ISSUE TITLE
CPP526 Lab 6 Step 3

### ISSUE THREAD

**Issue by ashleycc33** [Watts-College/cpp-526-spr-2023#18]
Hi there! Has anyone else been getting this issue for Lab 6 Step 3:
Error in mutate(., cost.per.win = (total_sal/Teams$W)/100000) : 
Caused by error:
! `cost.per.win` must be size 2985 or 1, not 918.

**Comment by ashleycc33** [comment]
Fixed this. Ended up having issues on Step 4 though

**Comment by kphart2** [comment]
Hi Ashley, how did you fix this? I'm having the exact same issue.
