### ISSUE TITLE
Module 7 Dashboard Instructions Question: 

### ISSUE THREAD

**Issue by tdeconcini** [Watts-College/cpp-526-spr-2023#19]
Hello, I am a little confused by the instructions for the dashboard. It says the dashboard should have six tabs, four of which have already been provided. Are the TABS that are already provided the "Day & Time", "Age, Gender, & Method", "Comparisons", "About", and "Data"? Where are we supposed to add these tabs, and what is the differentiation with the value boxes? Can someone please provide some guidance and any examples for reference?

**Comment by haileyjudd** [comment]
I believe the provided, completed tabs are the "Day & Time", "Age, Gender, & Method", "Comparisons", and "Data - as you don't have to do anything to them. You will need to make edits in the text on the "About" tab. 

From what I understand, you can add in the your other two tabs wherever they best fit within the dashboard. You can just copy/post the input and output sections to create your own tabs where you'd like them (or you can create them from scratch if you prefer).

What do you mean by value boxes?

**Comment by tdeconcini** [comment]
Hello! Thanks for responding, I figured it out, but I really appreciate your help!
