### ISSUE TITLE
Are the challenge questions optional? 

### ISSUE THREAD

**Issue by tdeconcini** [Watts-College/cpp-526-spr-2023#2]
Although I have already submitted the Lab sans challenge questions, I wanted to confirm that they were optional; It seems that they are based on the instructions in the lab template, but please correct me if this is wrong! 

Thanks, 
Tessa

**Comment by drcarlson-asu** [comment]
Hi Tessa,
That is correct. They are optional to try and get you thinking about how to apply your new knowledge.
~Dr. C

**Comment by tdeconcini** [comment]
Thanks so much!
