### ISSUE TITLE
Module 3

### ISSUE THREAD

**Issue by ndwilliams01** [Watts-College/cpp-526-spr-2023#3]
Hi, everyone! I'm very new to R, so I appreciate your patience. I don't understand how to highlight the league average by year for the graph. Here is the code I'm using for that particular section of the code. The last portion is where I am trying to highlight. This does absolutely nothing to the graph. 

ave.so <- Teams$SO / Teams$G                      # Calculating average strikeouts per game
year <- Teams$yearID                              # Extracting a vector of years per team

ave.so.min <- min(ave.so, na.rm = TRUE)
ave.so.max <- max(ave.so, na.rm = TRUE)           # Minimum and maximum x-axis limits

league.ave <- tapply(X = ave.so, 
                     INDEX = as.factor(year), 
                     FUN = "mean", 
                     na.rm = TRUE)                # Calculating league strikeout average/season

league.year <- as.numeric(names(league.ave))      # Ensuring years are numeric, not text
Teams$ave.so<-Teams$SO/Teams$G

year.jitter<-Teams$yearID +rnorm(nrow(Teams))
ave.so.jitter<-Teams$ave.so +rnorm(nrow(Teams))

plot.new()
plot.window(xlim = c(1900, 2012),   # Specify x-axis limits 
             ylim = c(ave.so.min, 
                    ave.so.max))   # Specify y-axis limits
points(x = year.jitter, 
        y = ave.so.jitter,
        col = "gray85",              # Color
        pch = 16,                    # Shape
        cex = 0.75)   
 
 axis(side = 1,                      # Add x-axis at bottom
      lwd = 2,                       # Line width
      hadj = -0.1,                   # Horizontal label position 
      padj = -1,                     # Vertical label position
      at = seq(from = 1900, 
               to = 2010, 
               by = 10))             # Specify tick label sequence
 
axis(side = 4,                      # Add y-axis to right side
      lwd = 0,                       # Remove axis line
      las = 1,                       # Rotate labels
      col.axis = "gray85",           # Adjust label colors
      at = seq(from = 0,             # Specify axis values
               to = 9, 
               by = 1), 
      font.axis = 2)                 # Set labels to bold
 
 title( main="Strikeouts on the Rise", adj=0)
mtext("There were more strikeouts in 2012 than at any other time in major league history.", adj=0, line=-1, cex=0.75)

grid(nx=NA,
     ny=9, 
     lty=2,
     col="gray",
     lwd=2)

#highlighting the league average - THIS DOESN'T DO ANYTHING TO THE GRAPH.
points(year.jitter[league.ave],                   
       ave.so.jitter[league.ave], 
       pch=19, cex=2, col="skyblue")

**Comment by drcarlson-asu** [comment]
Hi Nichola,
I see you closed this. What was the issue here and maybe you can share your resolution in case anybody else runs into something similar?
