### ISSUE TITLE
Module 3 Lab - Plot Limits + Legend

### ISSUE THREAD

**Issue by kybrwallace** [Watts-College/cpp-526-spr-2023#4]
Hey y'all, I'm having some trouble with the lab for module 3. I'm just about done, but I'm having two issues. 

**First**, for some reason my plot limits don't seem to be accurate. I have xlim = c(1900,2012), but it's plotting data from a few years before 1900 and a few years after 2012. I'm going to attach a screenshot also.

ave.so <- Teams$SO / Teams$G        # Average strike-outs per game each season 
year <- Teams$yearID

Teams$ave.so <- Teams$SO / Teams$G

ave.so.min <- min( ave.so, na.rm=T )
ave.so.max <- max( ave.so, na.rm=T )

plot.new()

plot.window(xlim = c(1900, 2012), 
            ylim = c(ave.so.min, 
                     ave.so.max))

![Mod3Chunk](https://user-images.githubusercontent.com/121522107/215248226-7051a221-de25-4045-9d4c-02645325b355.png)

My second issue is that I can't get the legend to display a line with 2 points. This is what I have so far. I've been googling this and going through the class resources but haven't found the answer. Any advice is appreciated.

legend(x = 1895,
       y = 9, 
       legend = "League average",
       col = "deepskyblue4", 
       lty = 1,
       cex=0.5,
       pch = 16,
       bty = "n")

**Comment by drcarlson-asu** [comment]
Hello,
No worries about the first issue. Your code looks fine there, so I wouldn't worry about the looks of that graph.
For the second issue, you need to instantiate another point. Here is an example of how I would approach this:

legend(x = 1895,
       y = 9,
       legend = c('League average', select.team),
       lty = c(1, 1),
       col = c('deepskyblue4', 'orange'),
       text.col = c('deepskyblue4', 'orange'),
       cex = 0.5,
       bty = 'n',
       box.col = 'white'
       )

**Comment by kybrwallace** [comment]
Thank you Dr. Carlson!
