### ISSUE TITLE
Lab 3 Issue Overview

### ISSUE THREAD

**Issue by tdeconcini** [Watts-College/cpp-526-spr-2023#8]
1) Struggled a lot with getting the gridlines to match up with the y-axis values...kept getting error messages about issues with the argument 
2) Struggled with being able to view the connecting lines that I added in to connect the annotations and points
3) Struggled getting the axis labels to go all the way across the plot window

I tried to troubleshoot these issues SO MUCH and just could not get them exactly right. Some correction and advice here would be appreciated for future projects.

**Comment by drcarlson-asu** [comment]
Hi Tessa,
I'm not sure why, but I wasn't receiving notifications for posts here lately. So I am just seeing this. Did you have a chance to review the answer page for Lab 3 yet? Hopefully that helped hit home some of the issues you were facing?
~Dr. C
